create table "Users" (
	"UserId" int generated by default as identity primary key,
	"UserName" varchar(50),
	"FirstName" varchar(50),
	"LastName" varchar(50),
	"IsActive" bool,
	"Gender" varchar(50),
	"Citizenship" varchar(50),
	"Ethnisity" varchar(50),
	"Email" varchar(50),
	"MobilePhone" varchar(10),
	"IDCardNumber" varchar(20),
	"NPI" varchar(10),
	"BirthDate" Date,
	"BirthCity" varchar(50),
	"BirthCountry" varchar(50),
	"HomeAddress" varchar(50),
	"HomeCity" varchar(50),
	"HomeCountry" varchar(50),
	"HomeZip" varchar(50),
	"HomePhone" varchar(10)
);

create table "Positions" (
	"PositionId" int generated by default as identity primary key,
	"PositionName" varchar(50),
	"PositionDescription" varchar(200),
	"PositionType" int,
	"Salary" int,
	"IsActive" bool
);

alter table "Users"
add column "PositionId" int not null default 1;

alter table "Users"
add constraint "FK_Positions_PositionId" foreign key ("PositionId") 
references "Positions" ("PositionId");
